# Generated by Django 5.0.6 on 2024-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_prayercategory_prayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer',
            name='prayer_request',
        ),
        migrations.AddField(
            model_name='prayer',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
