# Generated by Django 5.0.6 on 2024-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_book_number_alter_book_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testament',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testament',
            name='name',
            field=models.CharField(choices=[('New', 'New Testament'), ('Old', 'Old Testament')], default='Old', max_length=3),
        ),
    ]
