# Generated by Django 5.0.6 on 2024-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_alter_testament_id_alter_testament_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number',
        ),
        migrations.AlterField(
            model_name='bible',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testament',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verse',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verse',
            name='number',
            field=models.IntegerField(),
        ),
    ]
