# Generated by Django 5.0.6 on 2024-06-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0006_userreadingprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreadingprogress',
            old_name='date_read',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='userreadingprogress',
            name='verse',
        ),
        migrations.AddField(
            model_name='userreadingprogress',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
